spring.application.name=ecommerce

# ==============================
# H2 Database Configuration
# ==============================

# Enable the H2 database web console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configure in-memory H2 database

#the database will be created inmemory temporary ,lost on restart
spring.datasource.url=jdbc:h2:mem:test

# defines the driver class used to connect to the h2database
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.username=sa
spring.datasource.password=

# tells hiberate which sql dialect to use,this helps hibernate generate sql queries compatible with h2 syntax,
# If you miss the below h2-console wont be visible.
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# ==============================
# JPA & Hibernate Settings
# ==============================

# Show SQL queries in the console
spring.jpa.show-sql=true

# Format SQL output for readability
spring.jpa.properties.hibernate.format_sql=true

# Automatically create/update tables without dropping existing data
spring.jpa.hibernate.ddl-auto=update

# Product Image url to be displayed in the frontend:-
image.base.url=http://localhost:8080/images
